function [ mean_fft std_fft ] = mean_fft( time_sf )
%function [ mean_fft std_fft ] = mean_fft( time_sf )
% return the mean & std of the fft computed given a matrix generated by 
%  the function audio_time_fft
% 
%  see also: audio_time_fft
%
%

sizeF = size( time_sf ) ;

mean_fft = zeros( sizeF(3) , sizeF(2) ) ;
std_fft = zeros( sizeF(3) , sizeF(2) ) ;

for i=1:sizeF(3)
    b = time_sf(:,:,i) ;
    mean_fft(i,:) = mean( b ) ;
    std_fft = std( b ) ;
end

end

