function [ mean_fft std_fft ] = mean_fft( time_sf )
%function [ mean_fft std_fft ] = mean_fft( time_sf )
% return the mean & std of the fft
%  given a matrix generated by 
%  the function audio_time_fft
% 
%  see also: audio_time_fft
%
%

sizeF = size( time_sf ) ;

if size( sizeF , 2 ) == 2
    s3 = 1 ;
    s2 = sizeF(2) ;
else
    s3 = sizeF(3) ;
    s2 = sizeF(2) ;    
end

    mean_fft = zeros( s3 , s2 ) ;
    std_fft = zeros( s3 , s2 ) ;

for i=1:s3
    b = time_sf(:,:,i) ;
    mean_fft(i,:) = mean( b ) ;
    std_fft(i,:) = std( b ) ;
end

end

